version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: danilvdovin/foodgram_backend:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: danilvdovin/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_value/
      - media_value:/var/html/media_value/
      - ../frontend/:/app/result_build/
    depends_on:
      - backend


volumes:
  postgresql_data:
  static_value:
  media_value: