# Generated by Django 3.2.18 on 2023-04-11 08:46

import colorfield.fields
import core.limits
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(core.limits.Limits['MIN_COOKING_TIME'], message='Нужен хотя бы один ингредиент!'), django.core.validators.MaxValueValidator(core.limits.Limits['MAX_AMOUNT_INGREDIENTS'], message='Слишком много!')], verbose_name='Количество ингредиентов')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Количество ингридиентов',
                'ordering': ('recipe',),
            },
        ),
        migrations.CreateModel(
            name='BuyLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Рецепт в списке покупок',
                'verbose_name_plural': 'Рецепты в списке покупок',
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=core.limits.Limits['LEN_NAME_LIMIT'], verbose_name='Название')),
                ('measurement_unit', models.CharField(max_length=core.limits.Limits['LEN_NAME_LIMIT'], verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=core.limits.Limits['LEN_NAME_LIMIT'], verbose_name='Название блюда')),
                ('text', models.TextField(max_length=core.limits.Limits['LEN_TEXT_LIMIT'], verbose_name='Описание')),
                ('image', models.ImageField(upload_to='recipe_images/', verbose_name='Иллюстрация')),
                ('cooking_time', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(core.limits.Limits['MIN_COOKING_TIME'], 'Ваше блюдо уже готово!'), django.core.validators.MaxValueValidator(core.limits.Limits['MAX_COOKING_TIME'], 'Очень долго ждать...')], verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=core.limits.Limits['LEN_NAME_LIMIT'], unique=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=core.limits.Limits['LEN_HEX_CODE_LIMIT'], samples=None, unique=True, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField(max_length=core.limits.Limits['LEN_NAME_LIMIT'], unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
    ]
