# Generated by Django 3.2.18 on 2023-04-08 10:05

import colorfield.fields
import core.limits
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230406_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=core.limits.Limits['LEN_HEX_CODE_LIMIT'].value, samples=None, unique=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
